import type {
  Activity,
  BudgetTrip,
  Destination,
  PackingTemplate,
} from '../types'

// Beispieldaten, damit die App beim ersten Start nicht komplett leer ist.
// Alles kann in der App gelöscht/angepasst werden.

export const SEED_DESTINATIONS: Destination[] = [
  {
    id: 'dest-fuerteventura',
    name: 'Fuerteventura',
    land: 'Spanien (Kanaren)',
    notizen: 'Kurzer Flug ab Deutschland, ganzjährig warm, gute Infrastruktur.',
    ratings: {
      warm: 5,
      meer: 5,
      alleinMitBaby: 4,
      medizinischeVersorgung: 4,
      sicherheit: 5,
      kinderfreundlich: 4,
    },
    status: 'shortlist',
    klima: {
      besteMonate: [4, 5, 6, 9, 10],
      nebensaisonMonate: [11, 1, 2, 3],
      temperaturSommerC: 27,
      temperaturWinterC: 20,
      preisNotizen: 'Nebensaison (Nov–März, außer Weihnachten/Neujahr) oft 20–30% günstiger als Hochsommer.',
    },
    erstelltAm: new Date().toISOString(),
  },
  {
    id: 'dest-mallorca',
    name: 'Mallorca',
    land: 'Spanien (Balearen)',
    notizen: 'Sehr gute medizinische Versorgung, viele Familienhotels, kurze Flugzeit.',
    ratings: {
      warm: 4,
      meer: 5,
      alleinMitBaby: 5,
      medizinischeVersorgung: 5,
      sicherheit: 5,
      kinderfreundlich: 5,
    },
    status: 'shortlist',
    klima: {
      besteMonate: [5, 6, 9],
      nebensaisonMonate: [4, 10, 11],
      temperaturSommerC: 28,
      temperaturWinterC: 15,
      preisNotizen: 'April/Oktober deutlich günstiger als Juli/August, Wetter meist noch gut.',
    },
    erstelltAm: new Date().toISOString(),
  },
  {
    id: 'dest-algarve',
    name: 'Algarve',
    land: 'Portugal',
    notizen: 'Ruhiger als Spanien-Hotspots, schöne Strände, gute Anbindung.',
    ratings: {
      warm: 4,
      meer: 5,
      alleinMitBaby: 4,
      medizinischeVersorgung: 4,
      sicherheit: 5,
      kinderfreundlich: 4,
    },
    status: 'idee',
    klima: {
      besteMonate: [5, 6, 9],
      nebensaisonMonate: [3, 4, 10, 11],
      temperaturSommerC: 26,
      temperaturWinterC: 16,
      preisNotizen: 'Nebensaison im Frühjahr/Herbst spürbar günstiger, weniger Trubel.',
    },
    erstelltAm: new Date().toISOString(),
  },
]

export const SEED_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    destinationId: 'dest-fuerteventura',
    name: 'Strandtag mit Sonnensegel/Pop-up-Zelt',
    kategorie: 'Strand',
    babyfreundlich: true,
    altersHinweis: 'Ab 0 Monate, auf Sonnenschutz achten',
    kostenNiveau: 1,
    notizen: 'Windgeschützte Buchten im Süden bevorzugen.',
  },
  {
    id: 'act-2',
    destinationId: 'dest-fuerteventura',
    name: 'Oasis Park (Tierpark)',
    kategorie: 'Ausflug',
    babyfreundlich: true,
    altersHinweis: 'Kinderwagentauglich',
    kostenNiveau: 2,
    notizen: 'Schattige Wege, Café vor Ort.',
  },
  {
    id: 'act-3',
    destinationId: 'dest-mallorca',
    name: 'Spaziergang Altstadt Palma',
    kategorie: 'Stadt',
    babyfreundlich: true,
    altersHinweis: 'Kinderwagengeeignet, viele Cafés',
    kostenNiveau: 1,
    notizen: 'Vormittags weniger Hitze/Trubel.',
  },
  {
    id: 'act-4',
    destinationId: 'dest-mallorca',
    name: 'Baby-Schwimmkurs im Hotel',
    kategorie: 'Kurs',
    babyfreundlich: true,
    altersHinweis: 'Ab 6 Monate, viele Familienresorts bieten das an',
    kostenNiveau: 2,
    notizen: 'Vorab beim Hotel erfragen/buchen.',
  },
]

export const SEED_PACKING_TEMPLATES: PackingTemplate[] = [
  {
    id: 'tpl-warm-kurz',
    name: 'Warmes Ziel, kurze Reise (bis 5 Tage)',
    minTage: 1,
    maxTage: 5,
    zielTyp: 'warm',
    items: [
      { id: 'i1', name: 'Bodys/Strampler (pro Tag 1–2)', menge: 8, kategorie: 'Kleidung Baby' },
      { id: 'i2', name: 'Sonnenhut Baby', menge: 1, kategorie: 'Sonnenschutz' },
      { id: 'i3', name: 'Baby-Sonnencreme LSF 50', menge: 1, kategorie: 'Sonnenschutz' },
      { id: 'i4', name: 'UV-Schutzanzug', menge: 1, kategorie: 'Sonnenschutz' },
      { id: 'i5', name: 'Windeln (Tagesbedarf x Tage + Puffer)', menge: 30, kategorie: 'Hygiene' },
      { id: 'i6', name: 'Feuchttücher', menge: 3, kategorie: 'Hygiene' },
      { id: 'i7', name: 'Fieberthermometer', menge: 1, kategorie: 'Gesundheit' },
      { id: 'i8', name: 'Fiebersaft/-zäpfchen (nach Absprache Kinderarzt)', menge: 1, kategorie: 'Gesundheit' },
      { id: 'i9', name: 'Reiseapotheke Baby', menge: 1, kategorie: 'Gesundheit' },
      { id: 'i10', name: 'Reisebett/Beistellbett (falls nicht vor Ort)', menge: 1, kategorie: 'Schlafen' },
      { id: 'i11', name: 'Sonnensegel/Pop-up-Zelt', menge: 1, kategorie: 'Strand' },
      { id: 'i12', name: 'Schwimmwindeln', menge: 6, kategorie: 'Strand' },
      { id: 'i13', name: 'Kinderwagen (leicht/Reisebuggy)', menge: 1, kategorie: 'Mobilität' },
      { id: 'i14', name: 'Trageschnalle/Tragetuch', menge: 1, kategorie: 'Mobilität' },
      { id: 'i15', name: 'Milchpulver/Beikost-Vorrat', menge: 1, kategorie: 'Ernährung' },
    ],
  },
  {
    id: 'tpl-warm-lang',
    name: 'Warmes Ziel, längere Reise (6–14 Tage)',
    minTage: 6,
    maxTage: 14,
    zielTyp: 'warm',
    items: [
      { id: 'i1', name: 'Bodys/Strampler (pro Tag 1–2)', menge: 14, kategorie: 'Kleidung Baby' },
      { id: 'i2', name: 'Sonnenhut Baby', menge: 1, kategorie: 'Sonnenschutz' },
      { id: 'i3', name: 'Baby-Sonnencreme LSF 50', menge: 2, kategorie: 'Sonnenschutz' },
      { id: 'i4', name: 'UV-Schutzanzug', menge: 2, kategorie: 'Sonnenschutz' },
      { id: 'i5', name: 'Windeln (vor Ort nachkaufen einplanen)', menge: 40, kategorie: 'Hygiene' },
      { id: 'i6', name: 'Feuchttücher', menge: 5, kategorie: 'Hygiene' },
      { id: 'i7', name: 'Fieberthermometer', menge: 1, kategorie: 'Gesundheit' },
      { id: 'i8', name: 'Reiseapotheke Baby (inkl. Elektrolyte)', menge: 1, kategorie: 'Gesundheit' },
      { id: 'i9', name: 'Impfpass/U-Heft', menge: 1, kategorie: 'Dokumente' },
      { id: 'i10', name: 'Auslandskrankenversicherung-Unterlagen', menge: 1, kategorie: 'Dokumente' },
      { id: 'i11', name: 'Reisebett/Beistellbett (falls nicht vor Ort)', menge: 1, kategorie: 'Schlafen' },
      { id: 'i12', name: 'Sonnensegel/Pop-up-Zelt', menge: 1, kategorie: 'Strand' },
      { id: 'i13', name: 'Schwimmwindeln', menge: 10, kategorie: 'Strand' },
      { id: 'i14', name: 'Kinderwagen (leicht/Reisebuggy)', menge: 1, kategorie: 'Mobilität' },
      { id: 'i15', name: 'Waschmittel-Pads (für Zwischenwäsche)', menge: 1, kategorie: 'Sonstiges' },
    ],
  },
  {
    id: 'tpl-kalt-kurz',
    name: 'Kälteres/wechselhaftes Ziel, kurze Reise',
    minTage: 1,
    maxTage: 5,
    zielTyp: 'kalt',
    items: [
      { id: 'i1', name: 'Zwiebellook-Kleidung', menge: 6, kategorie: 'Kleidung Baby' },
      { id: 'i2', name: 'Mütze + Söckchen', menge: 2, kategorie: 'Kleidung Baby' },
      { id: 'i3', name: 'Fleece-/Winteranzug', menge: 1, kategorie: 'Kleidung Baby' },
      { id: 'i4', name: 'Regenschutz für Kinderwagen', menge: 1, kategorie: 'Mobilität' },
      { id: 'i5', name: 'Windeln (Tagesbedarf x Tage + Puffer)', menge: 25, kategorie: 'Hygiene' },
      { id: 'i6', name: 'Feuchttücher', menge: 2, kategorie: 'Hygiene' },
      { id: 'i7', name: 'Fieberthermometer', menge: 1, kategorie: 'Gesundheit' },
      { id: 'i8', name: 'Reiseapotheke Baby', menge: 1, kategorie: 'Gesundheit' },
      { id: 'i9', name: 'Reisebett/Beistellbett (falls nicht vor Ort)', menge: 1, kategorie: 'Schlafen' },
    ],
  },
]

export const SEED_BUDGET_TRIPS: BudgetTrip[] = [
  {
    id: 'budget-cp-1',
    typ: 'centerparcs',
    titel: 'Center Parcs Trip (national)',
    jahr: new Date().getFullYear(),
    kategorien: [
      { id: 'c1', name: 'Unterkunft', geplantEUR: 600, tatsaechlichEUR: 0 },
      { id: 'c2', name: 'Anreise (Auto/Bahn)', geplantEUR: 80, tatsaechlichEUR: 0 },
      { id: 'c3', name: 'Verpflegung', geplantEUR: 200, tatsaechlichEUR: 0 },
      { id: 'c4', name: 'Aktivitäten vor Ort', geplantEUR: 100, tatsaechlichEUR: 0 },
    ],
    notizen: 'Primär zum Meilen-/Punktesammeln über Buchungsplattform/Kreditkarte buchen.',
  },
  {
    id: 'budget-intl-1',
    typ: 'international',
    titel: 'Internationale Reise',
    jahr: new Date().getFullYear(),
    kategorien: [
      { id: 'c1', name: 'Flüge', geplantEUR: 500, tatsaechlichEUR: 0 },
      { id: 'c2', name: 'Unterkunft', geplantEUR: 900, tatsaechlichEUR: 0 },
      { id: 'c3', name: 'Verpflegung', geplantEUR: 400, tatsaechlichEUR: 0 },
      { id: 'c4', name: 'Transfer/Mietwagen', geplantEUR: 150, tatsaechlichEUR: 0 },
      { id: 'c5', name: 'Versicherung', geplantEUR: 60, tatsaechlichEUR: 0 },
      { id: 'c6', name: 'Aktivitäten/Ausflüge', geplantEUR: 150, tatsaechlichEUR: 0 },
    ],
    notizen: 'Meilen-Rechner nutzen, um Bar- vs. Meilenzahlung für den Flug abzuwägen.',
  },
]
